Lists are the R objects which contain elements of different types like − numbers, strings, vectors and another list inside it. A list can also contain a matrix or a function as its elements. List is created using list() function.

**Creating a List**

Following is an example to create a list containing strings, numbers, vectors and a logical values.
![](https://lh3.googleusercontent.com/-9KOWjtskLOg/XM-NgdPi4qI/AAAAAAAAFMM/ZfuYU2sBtLMK1ABk9BM2jzOzs7wEazodQCK8BGAs/s0/2019-05-05.png)

In [1]:
list_data <- list("Red", "Green", c(21,32,11), TRUE, 51.23, 119.1)
list_data

[[1]]
[1] "Red"

[[2]]
[1] "Green"

[[3]]
[1] 21 32 11

[[4]]
[1] TRUE

[[5]]
[1] 51.23

[[6]]
[1] 119.1

**Naming List Elements**
The list elements can be given names and they can be accessed using these names.

In [2]:
# Create a list containing a vector, a matrix and a list.
list_data <- list(10,c("Jan","Feb","Mar"), matrix(c(3,9,5,1,-2,8), nrow = 2),
   list("green",12.3))
list_data

[[1]]
[1] 10

[[2]]
[1] "Jan" "Feb" "Mar"

[[3]]
     [,1] [,2] [,3]
[1,]    3    5   -2
[2,]    9    1    8

[[4]]
[[4]][[1]]
[1] "green"

[[4]][[2]]
[1] 12.3

In [3]:
# Give names to the elements in the list.
names(list_data) <- c("1st Quarter", "A_Matrix", "A Inner list")

# Show the list.
list_data

$`1st Quarter`
[1] 10

$A_Matrix
[1] "Jan" "Feb" "Mar"

$`A Inner list`
     [,1] [,2] [,3]
[1,]    3    5   -2
[2,]    9    1    8

$<NA>
$<NA>[[1]]
[1] "green"

$<NA>[[2]]
[1] 12.3

**Accessing List Elements**

Elements of the list can be accessed by the index of the element in the list. In case of named lists it can also be accessed using the names.

In [6]:
# Create a list containing a vector, a matrix and a list.
list_data <- list(c("Jan","Feb","Mar"), matrix(c(3,9,5,1,-2,8), nrow = 2),list("green",12.3))
list_data

[[1]]
[1] "Jan" "Feb" "Mar"

[[2]]
     [,1] [,2] [,3]
[1,]    3    5   -2
[2,]    9    1    8

[[3]]
[[3]][[1]]
[1] "green"

[[3]][[2]]
[1] 12.3

In [9]:
# Give names to the elements in the list.
names(list_data) <- c("1st Quarter", "A_Matrix", "A Inner list")

# Access the first element of the list.
print(list_data[1])

$`1st Quarter`
[1] "Jan" "Feb" "Mar"



In [11]:
# Access the thrid element. As it is also a list, all its elements will be printed.
print(list_data[3])

$`A Inner list`
$`A Inner list`[[1]]
[1] "green"

$`A Inner list`[[2]]
[1] 12.3




In [12]:
# Access the list element using the name of the element.
print(list_data$A_Matrix)

     [,1] [,2] [,3]
[1,]    3    5   -2
[2,]    9    1    8


**Manipulating List Elements**

We can add, delete and update list elements as shown below. We can add and delete elements only at the end of a list. But we can update any element.

In [15]:
# Create a list containing a vector, a matrix and a list.
list_data <- list(c("Jan","Feb","Mar"), matrix(c(3,9,5,1,-2,8), nrow = 2),
   list("green",12.3))
list_data

[[1]]
[1] "Jan" "Feb" "Mar"

[[2]]
     [,1] [,2] [,3]
[1,]    3    5   -2
[2,]    9    1    8

[[3]]
[[3]][[1]]
[1] "green"

[[3]][[2]]
[1] 12.3

In [17]:
# Give names to the elements in the list.
names(list_data) <- c("1st Quarter", "A_Matrix", "A Inner list")

# Add element at the end of the list.
list_data[4] <- "New element"
print(list_data[4])


$<NA>
[1] "New element"



In [20]:
# Remove the last element.
list_data[4] <- NULL

# Print the 4th Element.
print(list_data[4])

$<NA>
NULL



In [21]:

# Update the 3rd Element.
list_data[3] <- "updated element"
print(list_data[3])


$`A Inner list`
[1] "updated element"



**Merging Lists**

You can merge many lists into one list by placing all the lists inside one list() function.

In [23]:
# Create two lists.
list1 <- list(1,2,3)
list2 <- list("Sun","Mon","Tue")

# Merge the two lists By using Vectore.
merged.list <- c(list1,list2)

# Print the merged list.
merged.list

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] "Sun"

[[5]]
[1] "Mon"

[[6]]
[1] "Tue"

`Converting List to Vector`
A list can be converted to a vector so that the elements of the vector can be used for further manipulation. All the arithmetic operations on vectors can be applied after the list is converted into vectors. To do this conversion, we use the unlist() function. It takes the list as input and produces a vector.

In [24]:
# Create lists.
list1 <- list(1:5)
print(list1)

list2 <-list(10:14)
print(list2)

[[1]]
[1] 1 2 3 4 5

[[1]]
[1] 10 11 12 13 14



In [25]:
# Convert the lists to vectors.
v1 <- unlist(list1)
v2 <- unlist(list2)

print(v1)
print(v2)

[1] 1 2 3 4 5
[1] 10 11 12 13 14


In [26]:
# Now add the vectors
result <- v1+v2
print(result)

[1] 11 13 15 17 19
